In [1]:
import numpy as np
import torch

group_size = 16
min_temp = 0.1
max_temp = 0.9

temperature = torch.linspace(min_temp, max_temp, steps=group_size)

temperature = torch.round(temperature, decimals=2)
print(temperature)


tensor([0.1000, 0.1500, 0.2100, 0.2600, 0.3100, 0.3700, 0.4200, 0.4700, 0.5300,
        0.5800, 0.6300, 0.6900, 0.7400, 0.7900, 0.8500, 0.9000])


In [10]:
group_size = 8
min_temp = 0.1
max_temp = 0.9
desired_step_size = 0.1

# Generate the sequence using the desired step size
steps = torch.arange(0, group_size) * desired_step_size
temperature = min_temp + steps

# Clamp values that exceed max_temp to max_temp
temperature = torch.clamp(temperature, min=min_temp, max=max_temp)
print(temperature)


tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000])


In [8]:
group_size = 64
min_temp = 0.1
max_temp = 0.9
step_sizes=[0.1, 0.05, 0.025, 0.01]

# Calculate the ideal step size based on the range and group size
temp_range = max_temp - min_temp
ideal_step_size = temp_range / (group_size - 1)  # -1 because we include both ends

# Select the largest step size from the list that is <= ideal_step_size
chosen_step_size = max([s for s in step_sizes if s <= ideal_step_size], default=step_sizes[-1])

print(chosen_step_size)

0.01


In [9]:
# Generate the sequence using the desired step size
steps = torch.arange(0, group_size) * chosen_step_size
temperature = min_temp + steps

# Clamp values that exceed max_temp to max_temp
temperature = torch.clamp(temperature, min=min_temp, max=max_temp)
print(temperature)


tensor([0.1000, 0.1100, 0.1200, 0.1300, 0.1400, 0.1500, 0.1600, 0.1700, 0.1800,
        0.1900, 0.2000, 0.2100, 0.2200, 0.2300, 0.2400, 0.2500, 0.2600, 0.2700,
        0.2800, 0.2900, 0.3000, 0.3100, 0.3200, 0.3300, 0.3400, 0.3500, 0.3600,
        0.3700, 0.3800, 0.3900, 0.4000, 0.4100, 0.4200, 0.4300, 0.4400, 0.4500,
        0.4600, 0.4700, 0.4800, 0.4900, 0.5000, 0.5100, 0.5200, 0.5300, 0.5400,
        0.5500, 0.5600, 0.5700, 0.5800, 0.5900, 0.6000, 0.6100, 0.6200, 0.6300,
        0.6400, 0.6500, 0.6600, 0.6700, 0.6800, 0.6900, 0.7000, 0.7100, 0.7200,
        0.7300])
